In [2]:
import numpy as np


In [ ]:
n

In [5]:
import tensorflow
import gym
import pandas

In [3]:
tensorflow.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [11]:
csv = pandas.read_csv("Sever.csv")

In [28]:
ze =numpy.zeros([3,15])

In [29]:
ze

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
z1 = numpy.array([1,2,3])

In [93]:
for i in range(1,100):
    on1 = numpy.ones([10])
    cpu = on1 * 10
    mem = on1 * 20
    numpy.concatenate([cpu,mem],axis=0).reshape([2,10])

In [94]:
numpy.array([10,20]).repeat(10).reshape([2,10])

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20]])

In [95]:
request = [0,0]

In [99]:
request.__len__()

2

In [87]:
numpy.repeat(z1,15).reshape([z1.size,15])

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [57]:
    class Server_State:
        # 剩余资源
        def __init__(self,server_def=[0,0],server_cost = [0,0], 
                            server_used = numpy.zeros([2,15]),time = 15) -> None:
            # 资源
            # 持有资源
            self.possess = numpy.array(server_def)
            # 已用资源
            self.used = server_used
            # 可用资源
            self.available = numpy.repeat(self.possess,time)\
                .reshape([self.possess.size,time]) - server_used
            self.cost = numpy.array(server_cost)
            pass
        def allocate(self,server_use = numpy.zeros([2,15])):
            self.available -= server_use
            print("{a}",self.available)

In [58]:
st = Server_State([123,255],[1235,51555],numpy.ones([2,15]),15)

In [63]:
st.allocate(numpy.ones([2,10])+numpy.zeros([2,15]))

ValueError: operands could not be broadcast together with shapes (2,10) (2,15) 

In [67]:
numpy.zeros([2,15])+numpy.ones([2,10])

ValueError: operands could not be broadcast together with shapes (2,15) (2,10) 

In [68]:
on1 = numpy.ones([2,10])

In [72]:
numpy.concatenate((on1,numpy.zeros([2,5])),axis=1)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

In [74]:
st.available[0][0]

120.0

In [4]:
a = [[0,1],[0]]
a[0].__len__()

2

In [7]:
numpy.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
3*365

1095

In [10]:
73229/1095

66.875799086758

In [2]:
import numpy
numpy.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])